import { request } from './request';

export const endpoints = {
  fetchKullanici: () => request.get(`/kullanici`),
  mudurlukListele: () => request.get(`/mudurluk/listele`),
  mudurlukEkle: data => request.post(`/mudurluk/ekle`, data),
  mudurlukGuncelle: data => request.post(`/mudurluk/guncelle`, data),
  sikayetTurListele: () => request.get(`/sikayetTur/listele`),
  sikayetTurEkle: data => request.post(`/sikayetTur/ekle`, data),
  sikayetTurGuncelle: data => request.post(`/sikayetTur/guncelle`, data),
  kurulusTurListele: () => request.get(`/kurulusTur/listele`),
  kurulusTurEkle: data => request.post(`/kurulusTur/ekle`, data),
  kurulusTurGuncelle: data => request.post(`/kurulusTur/guncelle`, data),
  kurulusListele: () => request.get(`/kurulus/listele`),
  kurulusEkle: data => request.post(`/kurulus/ekle`, data),
  kurulusGuncelle: data => request.post(`/kurulus/guncelle`, data),
  sikayetKonuListele: () => request.get(`/sikayetKonu/listele`),
  sikayetKonuEkle: data => request.post(`/sikayetKonu/ekle`, data),
  sikayetKonuGuncelle: data => request.post(`/sikayetKonu/guncelle`, data),
  sikayetAltKonuListele: () => request.get(`/sikayetAltKonu/listele`),
  sikayetAltKonuEkle: data => request.post(`/sikayetAltKonu/ekle`, data),
  sikayetAltKonuGuncelle: data => request.post(`/sikayetAltKonu/guncelle`, data),
  duyuruListele: () => request.get(`/duyuru/listele`),
  duyuruEkle: data => request.post(`/duyuru/ekle`, data),
  duyuruGuncelle: data => request.post(`/duyuru/guncelle`, data),
  sikayetSablonListele: () => request.get(`/sikayetSablon/listele`),
  sikayetSablonEkle: data => request.post(`/sikayetSablon/ekle`, data),
  sikayetSablonGuncelle: data => request.post(`/sikayetSablon/guncelle`, data),
  sikayetDegerlendirmeListele: () => request.get(`/sikayetDegerlendirme/listele`),
  sikayetDegerlendirmeEkle: data => request.post(`/sikayetDegerlendirme/ekle`, data),
  sikayetDegerlendirmeGuncelle: data => request.post(`/sikayetDegerlendirme/guncelle`, data),
  bankaKullaniciListele: () => request.get(`/bankaKullanici/listele`),
  bankaKullaniciEkle: data => request.post(`/bankaKullanici/ekle`, data),
  bankaKullaniciGuncelle: data => request.post(`/bankaKullanici/guncelle`, data),
};
